services:
  app:
    build: ./backend
    volumes:
      - ./backend:/var/www
      - vendor_data:/var/www/vendor
    environment:
      APP_ENV: ${APP_ENV:-local}
      DB_HOST: ${DB_HOST:-db}
      DB_DATABASE: ${DB_DATABASE:-vacation}
      DB_USERNAME: ${DB_USERNAME:-vacation}
      DB_PASSWORD: ${DB_PASSWORD:-vacation}
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks: [ internal ]

  web:
    image: nginx:1.27-alpine
    volumes:
      - ./backend:/var/www
      - ./backend/docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    ports:
      - "8080:80"
    networks: [ internal ]

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: vacation
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: vacation
      MYSQL_PASSWORD: vacation
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "33066:3306"
    networks: [ internal ]

  node:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    networks: [ internal ]
    command: sh -c "npm install && npm run dev -- --host"

volumes:
  dbdata:
  vendor_data:

networks:
  internal: